name: Update Vue.js in dev branch

on:
  workflow_dispatch: null
  schedule:
    # UTC
    - cron: "0 21 * * *"

jobs:
  vue_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Update Vue.js
        run: ./data/js/update.sh
      - name: Config git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
      - name: Commit and push
        run: |
          if [[ -n $(git status --porcelain) ]]
          then
            git add .
            git commit -m 'Update Vue.js'
            git push
          else
            echo "Nothing to commit."
          fi
